[Checks]
block-opening-brace-space-before=off
double-semicolon=error
double-spaces=error
ellipsis=off
line-length=warn
naming-convention=off
no-space=off
note=off
space-before-paren=off
use-of-tabs=error
trailing-newlines=error
trailing-whitespace=error
unnecessary-string-template=error

[Disabler]
disable-by-inline-comments=true

[line-length]
max-line-length=130
ignore-comments=true

[naming-convention]
exceptions=UUID,

[note]
keywords=TODO,FIXME,
