option('active_parameter', type: 'boolean', value: false, description: 'Support activeParameter in signatureHelp')
option('debug_mem', type: 'boolean', value: false, description: 'Debug memory usage')
option('man_pages', type: 'feature', value: 'auto', description: 'Generate and install man pages.')
option('tests', type: 'boolean', value: true, description: 'Build tests.')
